# Generated by Django 5.1.6 on 2025-03-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_cooperatemember_core_line_of_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('Accountant', 'Accountant'), ('Administrative Assistant', 'Administrative Assistant'), ('Chief Executive Officer', 'Chief Executive Officer'), ('Chief Financial Officer', 'Chief Financial Officer'), ('Chief Operating Officer', 'Chief Operating Officer'), ('Cleaning Staff', 'Cleaning Staff'), ('Customer Service Representative', 'Customer Service Representative'), ('Data Analyst', 'Data Analyst'), ('Director', 'Director'), ('Executive Assistant', 'Executive Assistant'), ('Executive Producer', 'Executive Producer'), ('Human Resources Manager', 'Human Resources Manager'), ('IT Support Specialist', 'IT Support Specialist'), ('Legal Advisor', 'Legal Advisor'), ('Marketing Manager', 'Marketing Manager'), ('Operations Manager', 'Operations Manager'), ('Project Manager', 'Project Manager'), ('Public Relations Officer', 'Public Relations Officer'), ('Receptionist', 'Receptionist'), ('Sales Manager', 'Sales Manager'), ('Security Personnel', 'Security Personnel'), ('Software Developer', 'Software Developer'), ('Technical Support Specialist', 'Technical Support Specialist')], error_messages={'required': 'Position cannot be empty!'}, max_length=100),
        ),
    ]
