# Generated by Django 5.1.6 on 2025-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_staff_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='account_number',
            field=models.IntegerField(error_messages={'required': 'Account number cannot be empty!'}, unique=True),
        ),
    ]
