# Generated by Django 5.1.6 on 2025-03-31 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_staff_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperatemember',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_member', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualmember',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='individual_member', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
