# Generated by Django 5.1.6 on 2025-04-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_cooperatemember_creator_individualmember_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CooperateMember',
            new_name='CorperateMember',
        ),
    ]
