# Generated by Django 5.1.6 on 2025-04-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_cooperatemember_corperatemember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CorperateMember',
            new_name='CorporateMember',
        ),
    ]
