# Generated by Django 5.1.6 on 2025-04-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_corporatemember_date_of_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatemember',
            name='date_of_establishment',
            field=models.DateField(error_messages={'required': 'Date of establishment cannot be empty!'}),
        ),
    ]
