GENDER = [
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]
# Staff Positions
STAFF_POSITIONS = [
    ("Accountant", "Accountant"),
    ("Administrative Assistant", "Administrative Assistant"),
    ("Chief Executive Officer", "Chief Executive Officer"),
    ("Chief Financial Officer", "Chief Financial Officer"),
    ("Chief Operating Officer", "Chief Operating Officer"),
    ("Cleaning Staff", "Cleaning Staff"),
    ("Customer Service Representative", "Customer Service Representative"),
    ("Data Analyst", "Data Analyst"),
    ("Director", "Director"),
    ("Executive Assistant", "Executive Assistant"),
    ("Executive Producer", "Executive Producer"),
    ("Human Resources Manager", "Human Resources Manager"),
    ("IT Support Specialist", "IT Support Specialist"),
    ("Legal Advisor", "Legal Advisor"),
    ("Marketing Manager", "Marketing Manager"),
    ("Operations Manager", "Operations Manager"),
    ("Project Manager", "Project Manager"),
    ("Public Relations Officer", "Public Relations Officer"),
    ("Receptionist", "Receptionist"),
    ("Sales Manager", "Sales Manager"),
    ("Security Personnel", "Security Personnel"),
    ("Software Developer", "Software Developer"),
    ("Technical Support Specialist", "Technical Support Specialist"),
]


DIRECTOR_POSITIONS = [
    ("1st Vice President", "1st Vice President"),
    ("2nd Vice President", "2nd Vice President"),
    ("Director of Business Development", "Director of Business Development"),
    ("Executive Director", "Executive Director"),
    ("Executive Secretary", "Executive Secretary"),
    ("Finance Secretary/Treasurer", "Finance Secretary/Treasurer"),
    ("Legal Advisor", "Legal Advisor"),
    ("Legal Secretary", "Legal Secretary"),
    ("President", "President"),
    ("Publicity Secretary", "Publicity Secretary"),
    ("Secretary", "Secretary"),
    ("Treasurer", "Treasurer"),
]

TITLE = [
    ("Arch", "Arch."),
    ("Barr", "Barr."),
    ("Capt", "Capt."),
    ("Chief", "Chief"),
    ("Col", "Col."),
    ("Dr", "Dr."),
    ("Engr", "Engr."),
    ("Gen", "Gen."),
    ("Hon", "Hon."),
    ("Imam", "Imam"),
    ("King", "King"),
    ("Lt", "Lt."),
    ("Maj", "Maj."),
    ("Miss", "Miss"),
    ("Mr", "Mr."),
    ("Mrs", "Mrs."),
    ("Ms", "Ms."),
    ("Mx", "Mx."),
    ("Pastor", "Pastor"),
    ("Prince", "Prince"),
    ("Princess", "Princess"),
    ("Prof", "Prof."),
    ("Rabbi", "Rabbi"),
    ("Queen", "Queen"),
    ("Rev", "Rev."),
]
# Nationality
NATIONALITIES = [
    ("Algerian", "Algerian"),
    ("American", "American"),
    ("Argentinian", "Argentinian"),
    ("Australian", "Australian"),
    ("Austrian", "Austrian"),
    ("Bangladeshi", "Bangladeshi"),
    ("Belgian", "Belgian"),
    ("Brazilian", "Brazilian"),
    ("British", "British"),
    ("Canadian", "Canadian"),
    ("Chilean", "Chilean"),
    ("Chinese", "Chinese"),
    ("Colombian", "Colombian"),
    ("Czech", "Czech"),
    ("Danish", "Danish"),
    ("Dutch", "Dutch"),
    ("Egyptian", "Egyptian"),
    ("Emirati", "Emirati"),
    ("Ethiopian", "Ethiopian"),
    ("Finnish", "Finnish"),
    ("Filipino", "Filipino"),
    ("French", "French"),
    ("German", "German"),
    ("Ghanaian", "Ghanaian"),
    ("Greek", "Greek"),
    ("Hungarian", "Hungarian"),
    ("Indian", "Indian"),
    ("Indonesian", "Indonesian"),
    ("Iraqi", "Iraqi"),
    ("Israeli", "Israeli"),
    ("Italian", "Italian"),
    ("Japanese", "Japanese"),
    ("Jordanian", "Jordanian"),
    ("Kenyan", "Kenyan"),
    ("Kuwaiti", "Kuwaiti"),
    ("Lebanese", "Lebanese"),
    ("Malaysian", "Malaysian"),
    ("Mexican", "Mexican"),
    ("Moroccan", "Moroccan"),
    ("Nigerian", "Nigerian"),
    ("New Zealander", "New Zealander"),
    ("Norwegian", "Norwegian"),
    ("Omani", "Omani"),
    ("Other", "Other"),
    ("Pakistani", "Pakistani"),
    ("Peruvian", "Peruvian"),
    ("Polish", "Polish"),
    ("Portuguese", "Portuguese"),
    ("Qatari", "Qatari"),
    ("Romanian", "Romanian"),
    ("Russian", "Russian"),
    ("Saudi Arabian", "Saudi Arabian"),
    ("Singaporean", "Singaporean"),
    ("South African", "South African"),
    ("South Korean", "South Korean"),
    ("Spanish", "Spanish"),
    ("Sudanese", "Sudanese"),
    ("Swedish", "Swedish"),
    ("Swiss", "Swiss"),
    ("Syrian", "Syrian"),
    ("Thai", "Thai"),
    ("Turkish", "Turkish"),
    ("Tunisian", "Tunisian"),
    ("Ukrainian", "Ukrainian"),
    ("Ugandan", "Ugandan"),
    ("Venezuelan", "Venezuelan"),
    ("Vietnamese", "Vietnamese"),
    ("Zimbabwean", "Zimbabwean"),
]

NATURE_OF_BUSINESS = [
    ("Accounting & Auditing", "Accounting & Auditing"),
    ("Agriculture", "Agriculture"),
    ("Automobile & Machinery", "Automobile & Machinery"),
    ("Banking", "Banking"),
    ("Business Support Services", "Business Support Services"),
    ("Chemical & Pharmaceuticals", "Chemical & Pharmaceuticals"),
    ("Construction Materials", "Construction Materials"),
    ("Consulting", "Consulting"),
    ("Courier & Delivery Services", "Courier & Delivery Services"),
    ("E-commerce", "E-commerce"),
    ("Electricity & Power Supply", "Electricity & Power Supply"),
    ("Electronics & Electrical", "Electronics & Electrical"),
    ("Event Planning", "Event Planning"),
    ("Fashion Designer", "Fashion Designer"),
    ("Film & Television", "Film & Television"),
    ("Fintech", "Fintech"),
    ("Fishing", "Fishing"),
    ("Food & Beverage Manufacturing", "Food & Beverage Manufacturing"),
    ("Gaming & Esports", "Gaming & Esports"),
    ("Government & Public Administration", "Government & Public Administration"),
    ("Healthcare & Pharmaceuticals", "Healthcare & Pharmaceuticals"),
    ("Hospitality & Tourism", "Hospitality & Tourism"),
    ("Hotels & Resorts", "Hotels & Resorts"),
    ("Import & Export", "Import & Export"),
    ("Information & Communication Technology", "Information & Communication Technology"),
    ("Insurance", "Insurance"),
    ("Investment & Asset Management", "Investment & Asset Management"),
    ("IT Services & Support", "IT Services & Support"),
    ("Legal Services", "Legal Services"),
    ("Manufacturing & Industrial", "Manufacturing & Industrial"),
    ("Marketing & Advertising", "Marketing & Advertising"),
    ("Media & Entertainment", "Media & Entertainment"),
    ("Medical Devices & Equipment", "Medical Devices & Equipment"),
    ("Metal & Steel", "Metal & Steel"),
    ("Mining", "Mining"),
    ("Non-Profit & NGOs", "Non-Profit & NGOs"),
    ("Oil & Gas", "Oil & Gas"),
    ("Other", "Other"),
    ("Plastic & Rubber", "Plastic & Rubber"),
    ("Primary & Secondary Schools", "Primary & Secondary Schools"),
    ("Publishing & Printing", "Publishing & Printing"),
    ("Real Estate & Property Management", "Real Estate & Property Management"),
    ("Recruitment & HR Services", "Recruitment & HR Services"),
    ("Religious Organizations", "Religious Organizations"),
    ("Renewable Energy", "Renewable Energy"),
    ("Retail Trade", "Retail Trade"),
    ("Road Transport", "Road Transport"),
    ("Security Services", "Security Services"),
    ("Software Development", "Software Development"),
    ("Telecommunications", "Telecommunications"),
    ("Textile & Apparel", "Textile & Apparel"),
    ("Trade & Commerce", "Trade & Commerce"),
    ("Transportation & Logistics", "Transportation & Logistics"),
    ("Universities & Colleges", "Universities & Colleges"),
    ("Vocational & Technical Training", "Vocational & Technical Training"),
    ("Warehousing & Logistics", "Warehousing & Logistics"),
    ("Water Supply & Waste Management", "Water Supply & Waste Management"),
    ("Wholesale Trade", "Wholesale Trade"),
    ("Wellness & Fitness", "Wellness & Fitness"),
]

# Sorted Professions
PROFESSIONS = [
    ("Accountant", "Accountant"),
    ("Actor", "Actor"),
    ("Architect", "Architect"),
    ("Auditor", "Auditor"),
    ("Banker", "Banker"),
    ("Carpenter", "Carpenter"),
    ("Chef", "Chef"),
    ("Civil Engineer", "Civil Engineer"),
    ("Cybersecurity Analyst", "Cybersecurity Analyst"),
    ("Data Scientist", "Data Scientist"),
    ("Dentist", "Dentist"),
    ("Doctor", "Doctor"),
    ("Economist", "Economist"),
    ("Electrical Engineer", "Electrical Engineer"),
    ("Entrepreneur", "Entrepreneur"),
    ("Fashion Designer", "Fashion Designer"),
    ("Financial Advisor", "Financial Advisor"),
    ("Investment Analyst", "Investment Analyst"),
    ("Journalist", "Journalist"),
    ("Lawyer", "Lawyer"),
    ("Librarian", "Librarian"),
    ("Medical Lab Scientist", "Medical Lab Scientist"),
    ("Musician", "Musician"),
    ("Nurse", "Nurse"),
    ("Photographer", "Photographer"),
    ("Software Engineer", "Software Engineer"),
    ("Teacher", "Teacher"),
    ("Writer", "Writer"),
    ("Other", "Other"),
]

from django.core.validators import RegexValidator
reg_no_validator = RegexValidator(
    regex=r'^[A-Za-z0-9\-\/\.]+$',  # Allows letters, numbers, hyphens, slashes, and dots
    message="Registration number can only contain letters, numbers, '-', '/', and '.'"
)